branch-defaults:
  master:
    environment: production
    group_suffix: null
  qa:
    environment: test
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: NextClassApp
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
